export { useScrollLock } from './useScrollLock'
export { useClickOutside } from './useClickOutside'
export { useCarousel, type UseCarouselOptions } from './useCarousel'
export { useMediaQuery, useIsMobile } from './useMediaQuery'
export { useFavorites } from './useFavorites'
